    name: Test 3

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - shell: Rscript {0}
            run:  renv::restore()
          - run: Rscript evaluate_submission.R --exercise=3
